"use client";

import { useState } from "react";
import { Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { generateIncidentTriage } from "@/lib/actions/incidents";
import { timeAgo, cn } from "@/lib/utils";
import type { TriageResult } from "@/lib/ai/triage";

type Props = {
  incidentId: string;
  existingTriage: TriageResult | null;
  generatedAt: Date | null;
  model: string | null;
};

export function AITriageSection({
  incidentId,
  existingTriage,
  generatedAt,
  model,
}: Props) {
  const [loading, setLoading] = useState(false);
  // Holds triage returned from the action so the UI updates without a full
  // page reload — revalidatePath handles the server cache, this handles the
  // client-side state in the same render cycle.
  const [triage, setTriage] = useState<TriageResult | null>(existingTriage);
  const [triageAt, setTriageAt] = useState<Date | null>(generatedAt);
  const [triageModel, setTriageModel] = useState<string | null>(model);

  async function handleGenerate() {
    setLoading(true);
    const result = await generateIncidentTriage(incidentId);
    setLoading(false);

    if (!result.success) {
      toast.error(result.error);
      return;
    }

    setTriage(result.data);
    setTriageAt(new Date());
    setTriageModel(triageModel);
    toast.success("Triage generated");
  }

  return (
    <section className="mt-6">
      <div className="mb-3 flex items-center gap-2">
        <h2 className="text-sm font-medium text-foreground">AI Triage</h2>
        <Badge className="gap-1 bg-violet-500/10 text-violet-500 border-transparent text-[10px] px-1.5 py-0">
          <Sparkles className="size-3" />
          AI
        </Badge>
      </div>

      <div className="rounded-xl border border-border bg-card px-6 py-5">
        {!triage ? (
          // No triage yet — show the generate button centered in the card.
          <div className="flex flex-col items-center gap-3 py-4">
            <p className="text-sm text-muted-foreground">
              Generate an AI-assisted root cause analysis for this incident.
            </p>
            <Button
              size="lg"
              disabled={loading}
              onClick={handleGenerate}
              className={cn(
                "ai-glow-button h-10 gap-2 rounded-lg bg-card px-5 text-sm font-medium text-foreground hover:bg-card disabled:opacity-100",
                loading && "is-generating",
              )}
            >
              <Sparkles
                className={cn(
                  "size-4 text-primary",
                  loading && "animate-pulse",
                )}
              />
              {loading ? "Generating…" : "Generate AI Triage"}
            </Button>
          </div>
        ) : (
          // Triage exists — render the three sections and footer.
          <div className="space-y-5">
            <TriageBlock title="Root cause" content={triage.rootCause} />
            <TriageBlock title="Likely change" content={triage.likelyChange} />

            <div>
              <h3 className="mb-2 text-xs font-medium text-muted-foreground uppercase tracking-wide">
                Debug steps
              </h3>
              <ol className="space-y-1.5 list-decimal list-inside">
                {triage.debugSteps.map((step, i) => (
                  <li key={i} className="text-sm text-foreground">
                    {step}
                  </li>
                ))}
              </ol>
            </div>

            <p className="text-xs text-muted-foreground border-t border-border pt-4">
              Generated by {triageModel} • {timeAgo(triageAt)}
            </p>
          </div>
        )}
      </div>
    </section>
  );
}

function TriageBlock({ title, content }: { title: string; content: string }) {
  return (
    <div>
      <h3 className="mb-1 text-xs font-medium text-muted-foreground uppercase tracking-wide">
        {title}
      </h3>
      <p className="text-sm text-foreground">{content}</p>
    </div>
  );
}
